version: "3.4"

services:
  main:
    build:
      context: ../..
      target: app_main
      dockerfile: ./installer/prod/Dockerfile
    restart: unless-stopped
    environment:
      API_URL: ${API_URL:-https://api.dentest.tech}
    ports:
      - target: 3000
        published: ${HTTP_PORT:-80}
        protocol: tcp
    volumes:
      - ./build:/srv/app/build
    extra_hosts:
      - host.docker.internal:host-gateway
      - ${API_HOST:-api.dentest.local}:host-gateway
