name: Prod deploy
#on:
#  push:
#    tags: [ '*' ]
on: workflow_dispatch
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        env:
          DEPLOYER_AGENT_PRIVATE_KEY: ${{ secrets.PROD_DEPLOYER_AGENT_PRIVATE_KEY }}
          DEPLOY_TO: ${{ secrets.PROD_SERVER }}
          DEPLOY_DIR: ${{ secrets.PROD_DEPLOY_TO }}
          PORT: 3000
        run: sudo gem install capistrano && eval `ssh-agent -s` && ssh-add <(echo "$DEPLOYER_AGENT_PRIVATE_KEY") && cap production deploy
